language: node_js
node_js:
  - "6.2.2"
os:
  - osx
env:
  - TARGET_ARCH=x64
before_script:
  - npm install -g electron
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
