sudo: false
before_install:
  - brew update && brew install nvm
  - mkdir ~/.nvm && cp $(brew --prefix nvm)/nvm-exec ~/.nvm/
  - export NVM_DIR=~/.nvm && source $(brew --prefix nvm)/nvm.sh
  - nvm install 4.1.1
  - npm upgrade -g npm
install:
  - npm install
script:
  - npm test
after_script:
  - npm run release
os:
  - osx
